/* DO NOT EDIT THIS FILE - it is machine generated */
#include <D:\JAVA\include\jni.h>
/* Header for class native_method_NativeMethod */

#ifndef _Included_native_method_NativeMethod
#define _Included_native_method_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     native_method_NativeMethod
 * Method:    h
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_native_1method_NativeMethod_h
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
